#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# export GREP_COLOR='1;32'
# export GREP_OPTIONS='--color=auto --exclude-dir=.cvs --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn'
# export LSCOLORS=Gxfxcxdxbxegedabagacad
# export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
# export GOPATH=/Users/Xiaoxun/Documents/Workspace/go

# alias dme='eval "$(docker-machine env dev)"'
# alias docker-push='dme && ./gradlew clean installDist && docker build -t seanzxx/poi-service . && docker push seanzxx/poi-service'

alias brewU="sudo brew update && sudo brew upgrade && sudo brew cleanup && sudo chown -R root:wheel /usr/local"
